### ISSUE TITLE
[Urgent] Instruction on friday's tutorial

### ISSUE THREAD

**Issue by nevet** [cs2103jan2015-f10-2c/main#104]
Hello guys, sorry for this last minute email. I'm now in New York for some issues, so I will NOT be able to cover the tutorial today (if we have, actually I have no idea how we gonna handle Good Friday). So could you please send your work, i.e. the OODM, to me individually, with graphs and explanations via email? For your V0.3, I will check it later on my own computer.

Sorry for the inconvenience caused and thank you for your cooperations!

**Comment by andysohwz** [comment]
Hi Huang Da, no worries; there isn't any tutorial today. Have fun in New York! :D According to the module website...

Each student is to submit a document containing the following items:
- [T10.1] Your answers to (a), (b), or (c)
- [T10.4] A screenshot of your V0.3 running in your own computer and showing the 20 sample tasks you entered
- [T10.5] Issue tracker screenshots of i) V0.3 issues assigned to you ii) V0.4 issues assigned to you

Each team is to submit a document containing:
- [T10.2] Example code from your integration testing
- [T10.3] Some screenshots of your V0.3 product and a list of commands it supports at V0.3
- [T10.4] A screenshot of your repo’s commit history for V0.3

Name the individual file [team id][your name].pdf  and team submission [team id].pdf. Submit to appropriate folder in IVLE before week 11 Saturday 2359.

If you'd like, we will email you the work instead of uploading it to IVLE.

**Comment by andysohwz** [comment]
Additional note: All the best for your Palantir interview! :D
